<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Tufail-Vivo" failures="2" tests="2" name="ValidatingFails" time="19.049" errors="0" timestamp="2020-06-20T10:58:59 EDT">
  <testcase classname="Academy.FailedValidation" name="basePageNavigation1" time="1.196">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Academy.FailedValidation.basePageNavigation1(FailedValidation.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- basePageNavigation1 -->
  <testcase classname="Academy.FailedValidation" name="basePageNavigation1" time="3.637">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.io.File.<init>(File.java:279)
at resources.base.getscreenShotPath(base.java:69)
at Academy.Listeners.onTestFailure(Listeners.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- basePageNavigation1 -->
</testsuite> <!-- ValidatingFails -->
