<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Tufail-Vivo" failures="2" tests="4" name="ValidatingIds" time="18.67" errors="0" timestamp="2020-06-26T13:55:44 EDT">
  <testcase classname="Academy.FailedValidation" name="basePageNavigation1" time="1.061">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Academy.FailedValidation.basePageNavigation1(FailedValidation.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- basePageNavigation1 -->
  <testcase classname="Academy.Validation" name="ValidetingBanners" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Academy.Validation.ValidetingBanners(Validation.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- ValidetingBanners -->
  <testcase classname="Academy.Validation" name="basePageNavigation" time="0.636"/>
  <testcase classname="Academy.HomePage" name="basePageNavigation" time="16.021"/>
</testsuite> <!-- ValidatingIds -->
